#!/usr/bin/env python3
"""

vex is a command line program for saving changes to a project, switching
between different versions, and sharing those changes.

vex supports bash completion: run `complete -o nospace -C vex vex`

"""
import os, os.path
import sys
import subprocess
import tempfile

if sys.version_info.major < 3 or (sys.version_info.minor < 6)  or (sys.version_info.minor == 6  and sys.implementation.name != 'cpython'):
    print('Minimum Python 3.7 (or CPython 3.6')
    sys.exit(-1)
sys.path.append(os.path.split(os.path.abspath(__file__))[0])

from vexlib.commands import vex_cmd

vex_cmd.main(__name__)
